/**
 * Build script for Vercel Serverless Functions
 * 
 * Uses esbuild to bundle server code into self-contained .mjs files
 * that Vercel can serve as serverless functions.
 * 
 * This resolves @shared/* path aliases and bundles our code,
 * while keeping npm packages external (loaded from node_modules at runtime).
 */
import { build } from 'esbuild';
import path from 'path';
import { mkdir, rm } from 'fs/promises';

async function buildVercelFunctions() {
  console.log('Building Vercel serverless functions...');
  
  // Clean and create output directories
  await rm('api', { recursive: true, force: true });
  await mkdir('api/cron', { recursive: true });
  
  const commonOptions = {
    bundle: true,
    platform: 'node' as const,
    target: 'node18',
    format: 'esm' as const,
    // Keep npm packages external — Vercel installs them from package.json
    // Only bundle our own source files to resolve @shared/* aliases
    packages: 'external' as const,
    alias: {
      '@shared': path.resolve('shared'),
      '@': path.resolve('client/src'),
    },
    sourcemap: false,
    minify: false,
    logLevel: 'info' as const,
    // Ensure ESM output with proper extension
    outExtension: { '.js': '.mjs' },
    banner: {
      js: '// Auto-generated by build-vercel-api.ts — DO NOT EDIT\n',
    },
  };
  
  // 1. Build main API handler
  await build({
    ...commonOptions,
    entryPoints: ['server/vercel-api.ts'],
    outfile: 'api/index.mjs',
  });
  console.log('✅ api/index.mjs built');
  
  // 2. Build cron handler
  await build({
    ...commonOptions,
    entryPoints: ['server/vercel-cron.ts'],
    outfile: 'api/cron/check-alarms.mjs',
  });
  console.log('✅ api/cron/check-alarms.mjs built');
  
  console.log('🎉 All Vercel functions built successfully!');
}

buildVercelFunctions().catch(err => {
  console.error('❌ Vercel API build failed:', err);
  process.exit(1);
});

